

###
GET http://localhost:3002/home
Content-Type: application/json


###
POST http://pharmafine.herokuapp.com/users
Content-Type: application/json

{
    "name":"carlos",
    "lastname":"flores",
    "email":"carlos.flogars@gmail.com",
    "password":"1234"
}

###
PATCH https://pharmafine.herokuapp.com/users
Content-Type: application/json
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmlhQGdtYWlsLmNvbSIsImlhdCI6MTU4OTU4MTU3NSwiZXhwIjoxNTg5NTg1MTc1fQ.tYdV2BxQhrWxZnhLN_-A1yhggOvVZclUwekHkXSuuQc
email: maria@gmail.com

{
  "url": "ww33"
}

###
POST http://pharmafine.herokuapp.com/login
Content-Type: application/json

{
    "email":"carlos.flogars@gmail.com",
    "password":"1234"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "email":"maria@gmail.com",
  "password":"1234"
}

###
GET http://localhost:5000/products

###
GET http://localhost:5000/checkout
Content-Type: application/json
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmlhQGdtYWlsLmNvbSIsImlhdCI6MTU4OTU2ODE5NSwiZXhwIjoxNTg5NTcxNzk1fQ.pu_y79A_mge-fagJTOhNjnrjl1yYJZ9rgpM9IkzRNpU
email: maria@gmail.com

###
PATCH http://localhost:5000/checkout
Content-Type: application/json
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmlhQGdtYWlsLmNvbSIsImlhdCI6MTU4OTQyNTAwNSwiZXhwIjoxNTg5NDI4NjA1fQ.zRKPQNKI8gMaJEwLfNYQ19gn0SQycRlAs5NOPLCX1kE
email: maria@gmail.com

{
  "product": "0003",
  "quantity": "2"
}

###
DELETE http://localhost:5000/checkout
Content-Type: application/json
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmlhQGdtYWlsLmNvbSIsImlhdCI6MTU4OTU3NTkyOCwiZXhwIjoxNTg5NTc5NTI4fQ.-ahu1mLVP1it_-fu6g7S-OAhs7_guGYaLEZEEKzuIYE
email: maria@gmail.com
product: 0001


###
GET http://pharmafine.herokuapp.com/users
Content-Type: application/json
email: carlos.flogars@gmail.com
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhcmxvcy5mbG9nYXJzQGdtYWlsLmNvbSIsImlhdCI6MTU4OTU2MDM5OSwiZXhwIjoxNTg5NTYzOTk5fQ.sZu8a_joy_lRznpX8HdU3i9WBWFFepWxo1o-qwru-B0


###
GET http://localhost:3002/pay
Content-Type: application/json


###
DELETE http://localhost:3002/checkout
Content-Type: application/json
email: fernanda@gmail.com
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZlcm5hbmRhQGdtYWlsLmNvbSIsImlhdCI6MTU3NTM5MzkxOSwiZXhwIjoxNTc1Mzk3NTE5fQ.AL-kckugkrNcX1eFEvn_l9z7EEcicZmH8TKCpLrXRs4

{
    "products":["abc"]
}


###
GET http://localhost:3002/verifyEmailConfirmation?token=1234
Content-Type: application/json