

###
GET http://localhost:3002/home
Content-Type: application/json


###
POST http://pharmafine.herokuapp.com/users
Content-Type: application/json

{
    "name":"carlos",
    "lastname":"flores",
    "email":"carlos.flogars@gmail.com",
    "password":"1234"
}

###
POST http://pharmafine.herokuapp.com/login
Content-Type: application/json

{
    "email":"carlos.flogars@gmail.com",
    "password":"1234"
}

###
GET http://localhost:5000/products

###
GET http://localhost:3002/checkout
Content-Type: application/json
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhcmxvc0BnbWFpbC5jb20iLCJpYXQiOjE1NzU0OTk0NzgsImV4cCI6MTU3NTUwMzA3OH0.FnHWc1-KMcgM7omnCSjW1EqBq_JdlA9segR-jBCZCxk
email: carlos@gmail.com




###
GET http://pharmafine.herokuapp.com/users
Content-Type: application/json
email: maria@gmail.com
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmlhQGdtYWlsLmNvbSIsImlhdCI6MTU4OTA4ODI0NiwiZXhwIjoxNTg5MDg4NTQ2fQ.h-5poWTMz9PbaEXfguxhtJD2_HAUj3yc_5AisOR_rWg


###
GET http://localhost:3002/pay
Content-Type: application/json


###
DELETE http://localhost:3002/checkout
Content-Type: application/json
email: fernanda@gmail.com
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZlcm5hbmRhQGdtYWlsLmNvbSIsImlhdCI6MTU3NTM5MzkxOSwiZXhwIjoxNTc1Mzk3NTE5fQ.AL-kckugkrNcX1eFEvn_l9z7EEcicZmH8TKCpLrXRs4

{
    "products":["abc"]
}


###
GET http://localhost:3002/verifyEmailConfirmation?token=1234
Content-Type: application/json